import type { GeneratedExam, AnalysisResult } from './types';

export const DEMO_ANALYSIS: AnalysisResult = {
  subject: 'Datenbanksysteme',
  totalTaskTypes: 5,
  taskTypes: [
    { id: 'er_modell', name: 'ER-Modell', description: 'Entity-Relationship-Diagramme entwerfen und interpretieren', frequency: 25, avgPoints: 12, difficulty: 3, exampleQuestion: 'Entwerfe ein ER-Modell für ein Bibliothekssystem', hasdiagramContext: true },
    { id: 'sql', name: 'SQL-Abfragen', description: 'SELECT, JOIN, GROUP BY, Unterabfragen', frequency: 30, avgPoints: 15, difficulty: 3, exampleQuestion: 'Gib alle Kunden aus, die mehr als 3 Bestellungen haben', hasdiagramContext: false },
    { id: 'normalisierung', name: 'Normalisierung', description: '1NF, 2NF, 3NF, BCNF bestimmen und überführen', frequency: 20, avgPoints: 10, difficulty: 4, exampleQuestion: 'Überführe die Tabelle in die 3. Normalform', hasdiagramContext: false },
    { id: 'transaktionen', name: 'Transaktionen & ACID', description: 'ACID-Eigenschaften, Serialisierbarkeit, Sperren', frequency: 15, avgPoints: 8, difficulty: 4, exampleQuestion: 'Erkläre die ACID-Eigenschaften anhand eines Beispiels', hasdiagramContext: false },
    { id: 'indexe', name: 'Indexe & Optimierung', description: 'B-Baum-Indexe, Query-Optimierung', frequency: 10, avgPoints: 5, difficulty: 3, exampleQuestion: 'Welche Indexe würdest du für diese Abfrage anlegen?', hasdiagramContext: false },
  ],
  averageDifficulty: 3.2,
  estimatedDuration: 90,
  totalPoints: 50,
  topicAreas: ['ER-Modellierung', 'Relationale Algebra', 'SQL', 'Normalisierung', 'Transaktionsmanagement'],
  examCount: 3,
  hasSlideContext: false,
  slideTopics: [],
  hadImageOnlyContent: false,
};

export const DEMO_EXAM: GeneratedExam = {
  title: 'Probeklausur: Datenbanksysteme',
  duration: 90,
  totalPoints: 50,
  includedTypes: ['er_modell', 'sql', 'normalisierung', 'transaktionen'],
  excludedTypes: ['indexe'],
  tasks: [
    {
      id: 'task_1',
      number: 1,
      type: 'ER-Modell',
      typeId: 'er_modell',
      title: 'Entity-Relationship-Modell',
      description: 'Entwerfe ein ER-Modell für ein Online-Shop-System mit folgenden Anforderungen:\n\n- Kunden können mehrere Bestellungen aufgeben\n- Jede Bestellung enthält mindestens ein Produkt (mit Menge)\n- Produkte gehören zu genau einer Kategorie\n- Jede Kategorie kann Unterkategorien haben',
      points: 12,
      subTasks: [
        { label: 'a', text: 'Identifiziere alle Entitätstypen und ihre Attribute (mindestens 3 Attribute pro Entität).', points: 4 },
        { label: 'b', text: 'Bestimme alle Beziehungstypen mit Kardinalitäten (min, max) im Chen-Notation.', points: 5 },
        { label: 'c', text: 'Kennzeichne alle Primärschlüssel und erkläre zwei Fremdschlüsselbeziehungen.', points: 3 },
      ],
      hints: ['Achte auf schwache Entitätstypen', 'Die Menge in Bestellung-Produkt ist ein Beziehungsattribut'],
      hasDiagram: false,
      diagramDescription: '',
    },
    {
      id: 'task_2',
      number: 2,
      type: 'SQL-Abfragen',
      typeId: 'sql',
      title: 'SQL-Abfragen',
      description: 'Gegeben sei folgendes Datenbankschema:\n\n| Tabelle | Spalten |\n|---|---|\n| Kunde | KundeID, Name, Stadt, Email |\n| Bestellung | BestellID, KundeID, Datum, Status |\n| Position | PosID, BestellID, ProduktID, Menge, Preis |\n| Produkt | ProduktID, Name, Kategorie, Lagerbestand |\n\nFormuliere folgende SQL-Abfragen:',
      points: 15,
      subTasks: [
        { label: 'a', text: 'Gib Name und Stadt aller Kunden aus München aus, sortiert nach Name aufsteigend.', points: 3 },
        { label: 'b', text: 'Berechne den Gesamtumsatz (Summe aus Menge × Preis) je Kunde. Zeige nur Kunden mit Umsatz > 500 €.', points: 5 },
        { label: 'c', text: 'Liste alle Produkte mit Lagerbestand < 10, bei denen in den letzten 30 Tagen mindestens eine Bestellung eingegangen ist.', points: 4 },
        { label: 'd', text: 'Finde alle Kunden, die noch nie eine Bestellung aufgegeben haben (Unterabfrage oder LEFT JOIN).', points: 3 },
      ],
      hints: [],
      hasDiagram: false,
      diagramDescription: '',
    },
    {
      id: 'task_3',
      number: 3,
      type: 'Normalisierung',
      typeId: 'normalisierung',
      title: 'Normalisierung',
      description: 'Gegeben sei folgende unnormalisierte Relation:\n\n| BestellID | KundeName | KundeStadt | ProduktID | ProduktName | Kategorie | Menge | Einzelpreis |\n|---|---|---|---|---|---|---|---|\n| 1001 | Müller | Berlin | P01 | Laptop | Elektronik | 1 | 999,00 |\n| 1001 | Müller | Berlin | P02 | Maus | Elektronik | 2 | 15,00 |\n| 1002 | Schmidt | Hamburg | P01 | Laptop | Elektronik | 1 | 999,00 |\n| 1003 | Müller | Berlin | P03 | Stuhl | Büro | 1 | 120,00 |',
      points: 10,
      subTasks: [
        { label: 'a', text: 'Bestimme alle funktionalen Abhängigkeiten in der gegebenen Relation.', points: 3 },
        { label: 'b', text: 'Überführe die Relation schrittweise in die 1NF, 2NF und 3NF. Gib für jeden Schritt die resultierenden Tabellen mit Primärschlüsseln an.', points: 5 },
        { label: 'c', text: 'Begründe, ob die resultierende Relation in BCNF vorliegt.', points: 2 },
      ],
      hints: ['BestellID + ProduktID bilden den zusammengesetzten Primärschlüssel der Ausgangstabelle'],
      hasDiagram: false,
      diagramDescription: '',
    },
    {
      id: 'task_4',
      number: 4,
      type: 'Transaktionen & ACID',
      typeId: 'transaktionen',
      title: 'Transaktionen und Serialisierbarkeit',
      description: 'Betrachte folgende zwei Transaktionen, die gleichzeitig auf eine Datenbank zugreifen:\n\n| Schritt | T1 | T2 |\n|---|---|---|\n| 1 | read(A) | |\n| 2 | | read(A) |\n| 3 | A := A − 100 | |\n| 4 | write(A) | |\n| 5 | | A := A × 2 |\n| 6 | read(B) | write(A) |\n| 7 | | read(B) |\n| 8 | B := B + 100 | |\n| 9 | write(B) | B := B − 50 |\n| 10 | | write(B) |',
      points: 8,
      subTasks: [
        { label: 'a', text: 'Handelt es sich bei dem gezeigten Schedule um einen seriellen Schedule? Begründe.', points: 2 },
        { label: 'b', text: 'Überprüfe den Schedule auf Konfliktserialisierbarkeit. Zeichne den Konfliktgraphen und bestimme, ob ein äquivalenter serieller Schedule existiert.', points: 4 },
        { label: 'c', text: 'Welches ACID-Prinzip wird durch gleichzeitige unkontrollierte Ausführung verletzt? Nenne eine Lösung.', points: 2 },
      ],
      hints: ['Konfliktgraph: Knoten = Transaktionen, Kante = Konflikt zwischen Operationen'],
      hasDiagram: false,
      diagramDescription: '',
    },
    {
      id: 'task_5',
      number: 5,
      type: 'SQL-Abfragen',
      typeId: 'sql',
      title: 'Relationale Algebra & SQL',
      description: 'Gegeben seien die Relationen R(A, B, C) und S(C, D, E) mit folgenden Instanzen:\n\n**Relation R:**\n\n| A | B | C |\n|---|---|---|\n| 1 | x | 10 |\n| 2 | y | 20 |\n| 3 | x | 10 |\n| 4 | z | 30 |\n\n**Relation S:**\n\n| C | D | E |\n|---|---|---|\n| 10 | p | 100 |\n| 20 | q | 200 |\n| 50 | r | 500 |',
      points: 5,
      subTasks: [
        { label: 'a', text: 'Berechne R ⋈ S (Natural Join über Attribut C). Gib das Ergebnis als Tabelle an.', points: 2 },
        { label: 'b', text: 'Schreibe die äquivalente SQL-Abfrage für den Natural Join mit einer zusätzlichen Selektion σ_{B=\'x\'}(R) ⋈ S.', points: 3 },
      ],
      hints: [],
      hasDiagram: false,
      diagramDescription: '',
    },
  ],
  solution: [
    {
      taskId: 'task_1',
      solution: 'a) Entitätstypen:\n- Kunde: KundeID (PK), Name, Email, Adresse\n- Bestellung: BestellID (PK), Datum, Gesamtbetrag\n- Produkt: ProduktID (PK), Name, Preis, Lagerbestand\n- Kategorie: KategorieID (PK), Name, BeschreibungAusgabe\n\nb) Beziehungen:\n- Kunde (1,1) — aufgeben — (0,n) Bestellung\n- Bestellung (1,n) — enthalten — (0,n) Produkt [Beziehungsattribut: Menge]\n- Produkt (0,n) — gehört_zu — (1,1) Kategorie\n- Kategorie (0,1) — Unterkategorie_von — (0,n) Kategorie\n\nc) Fremdschlüssel:\n- Bestellung.KundeID → Kunde.KundeID\n- Position.ProduktID → Produkt.ProduktID',
      keyPoints: ['4 Entitätstypen korrekt identifiziert', 'Kardinalitäten im Chen-Stil (min,max)', 'Rekursive Beziehung bei Kategorie', 'Beziehungsattribut Menge erkannt'],
      commonMistakes: ['Menge als Attribut von Produkt statt Beziehungsattribut', 'Fehlende (0,1) bei rekursiver Kategorie-Beziehung', 'Falsche Kardinalitätsrichtung'],
    },
    {
      taskId: 'task_2',
      solution: 'a) SELECT Name, Stadt FROM Kunde WHERE Stadt = \'München\' ORDER BY Name ASC;\n\nb) SELECT k.Name, SUM(p.Menge * p.Preis) AS Umsatz\n   FROM Kunde k\n   JOIN Bestellung b ON k.KundeID = b.KundeID\n   JOIN Position p ON b.BestellID = p.BestellID\n   GROUP BY k.KundeID, k.Name\n   HAVING SUM(p.Menge * p.Preis) > 500;\n\nc) SELECT * FROM Produkt\n   WHERE Lagerbestand < 10\n   AND ProduktID IN (\n     SELECT p.ProduktID FROM Position p\n     JOIN Bestellung b ON p.BestellID = b.BestellID\n     WHERE b.Datum >= CURRENT_DATE - INTERVAL \'30 days\'\n   );\n\nd) SELECT * FROM Kunde\n   WHERE KundeID NOT IN (SELECT KundeID FROM Bestellung);',
      keyPoints: ['WHERE-Bedingung mit Stadtfilter', 'HAVING statt WHERE für aggregierte Bedingungen', 'Unterabfrage oder EXISTS für Teilaufgabe c', 'NOT IN oder LEFT JOIN ... WHERE IS NULL für Teilaufgabe d'],
      commonMistakes: ['WHERE statt HAVING für aggregierte Bedingungen', 'Vergessen GROUP BY bei SUM()', 'CURRENT_DATE Syntax variiert je DBMS'],
    },
    {
      taskId: 'task_3',
      solution: 'a) Funktionale Abhängigkeiten:\n- BestellID → KundeName, KundeStadt\n- ProduktID → ProduktName, Kategorie, Einzelpreis\n- BestellID, ProduktID → Menge\n\nb) 1NF: Bereits erfüllt (atomare Werte).\n\n2NF: Entferne partielle Abhängigkeiten vom zusammengesetzten Schlüssel:\n- Bestellung(BestellID, KundeName, KundeStadt)\n- Produkt(ProduktID, ProduktName, Kategorie, Einzelpreis)\n- Position(BestellID, ProduktID, Menge)\n\n3NF: Entferne transitive Abhängigkeiten:\n- KundeStadt hängt von KundeID ab → Kunde(KundeID, KundeName, KundeStadt)\n- Bestellung(BestellID, KundeID)\n\nc) BCNF: Ja, alle Determinanten sind Superschlüssel in den resultierenden Relationen.',
      keyPoints: ['Korrekte FDs identifiziert', 'Schrittweise Überführung 1→2→3NF', 'Position-Tabelle mit zusammengesetztem PK', 'BCNF-Begründung über Superschlüssel'],
      commonMistakes: ['Transitive Abhängigkeit KundeName→KundeStadt übersehen', '2NF-Schritt übersprungen', 'BCNF nicht von 3NF abgegrenzt'],
    },
    {
      taskId: 'task_4',
      solution: 'a) Nein, kein serieller Schedule. In einem seriellen Schedule würden alle Operationen von T1 vor T2 (oder umgekehrt) ausgeführt. Hier wechseln sich T1 und T2 ab.\n\nb) Konflikte:\n- r1(A) vor w2(A): T1→T2\n- r2(A) vor w1(A): T2→T1\n→ Konfliktgraph hat Zyklus T1↔T2\n→ Schedule ist NICHT konfliktserialisierbar.\n\nc) Verletzt wird die Isolation (I in ACID).\nLösung: Sperrprotokoll (2PL - Zwei-Phasen-Sperrprotokoll) oder MVCC.',
      keyPoints: ['Seriell korrekt verneint', 'Konfliktgraph mit Zyklusnachweis', 'Isolation als verletztes ACID-Prinzip', 'Konkreter Lösungsansatz genannt'],
      commonMistakes: ['Konsistenz statt Isolation genannt', 'Konfliktgraph-Richtung verwechselt', 'Zyklus nicht als Grund für Nicht-Serialisierbarkeit erklärt'],
    },
    {
      taskId: 'task_5',
      solution: 'a) Natural Join R ⋈ S (über C):\n\n| A | B | C  | D | E   |\n|---|---|----|---|-----|\n| 1 | x | 10 | p | 100 |\n| 2 | y | 20 | q | 200 |\n| 3 | x | 10 | p | 100 |\n\nTupel mit C=30 und C=50 haben kein Match → fallen raus.\n\nb) SELECT r.A, r.B, r.C, s.D, s.E\n   FROM R r\n   JOIN S s ON r.C = s.C\n   WHERE r.B = \'x\';',
      keyPoints: ['3 Ergebnistupel (C=10 zweimal, C=20 einmal)', 'C=30 und C=50 korrekt ausgelassen', 'SQL mit JOIN und WHERE-Bedingung'],
      commonMistakes: ['C=30 fälschlicherweise im Ergebnis', 'WHERE-Bedingung auf falsche Tabelle angewendet', 'Natural Join als CROSS JOIN interpretiert'],
    },
  ],
};
